desc "Run this lane when the CI environment handle a new build"
desc "#### Example:"
desc "```\nfastlane ci_framework_begin product_name:DGFrameworkTemplate\n```"
desc "#### Options"
desc "* **product_name**: The framework name."
desc "  * **environment_variable**: DG_PRODUCT_NAME"
desc "  * **type**: string"
desc "  * **optional**: true"
desc "* **project**: The project to use."
desc "  * **environment_variable**: DG_PROJECT"
desc "  * **type**: string"
desc "  * **optional**: true"
desc "* **skip_slack**: Skip slack notification even if a SLACK_URL is define."
desc "  * **type**: boolean"
desc "  * **optional**: true"
desc "  * **default_value**: false"
desc "#### Environment variables"
desc "* **SLACK_URL**: The slack Hook URL"
desc "  * **type**: string"
desc "  * **optional**: true"
desc ""
lane :ci_framework_begin do |options|
  if ENV['CI'] == nil
    UI.user_error! "Only a CI environment can run this lane"
  end
  prepare_lane_options(
    options: options,
    mapping: {
      :project => {:env_var => "DG_PROJECT"},
      :product_name => {:env_var => "DG_PRODUCT_NAME"}
    }
  )
  if options[:skip_slack] != true
    notification_payload = {
      "Git Branch" => git_branch(),
      "Version" => get_version_number(xcodeproj: options[:project]),
      "Platform" => "iOS"
    }
    if options[:product_name] != nil
      notification_payload["Framework"] = options[:product_name]
    end
    slack(
      message: "Starting Framework CI",
      payload: notification_payload,
      default_payloads: [:git_author]
    )
  end
end

desc "Build and run all tests in the CI environment"
desc "#### Example:"
desc "```\nfastlane ci_framework_tests workspace:NAME.xcworkspace\n```"
desc "#### How to install ?"
desc "This lane require actions define in [Digipolitan/fastlane-common](https://github.com/Digipolitan/fastlane-common)"
desc "```\nimport_from_git(\n  url: 'https://github.com/Digipolitan/fastlane-common'\n)\n```"
desc "#### Options"
desc "* **workspace**: The workspace to use."
desc "  * **environment_variable**: DG_WORKSPACE"
desc "  * **type**: string"
desc "  * **optional**: true"
desc "* **project**: The project to use."
desc "  * **environment_variable**: DG_PROJECT"
desc "  * **type**: string"
desc "  * **optional**: true"
desc "* **scheme**: The scheme into the workspace to execute."
desc "  * **environment_variable**: DG_SCHEME"
desc "  * **type**: string"
desc "  * **optional**: true"
desc "* **skip_slack**: Skip slack notification even if a SLACK_URL is define."
desc "  * **type**: boolean"
desc "  * **optional**: true"
desc "  * **default_value**: false"
desc "#### Environment variables"
desc "* **SLACK_URL**: The slack Hook URL"
desc "  * **type**: string"
desc "  * **optional**: true"
desc ""
lane :ci_framework_tests do |options|
  if ENV['CI'] == nil
    UI.user_error! "Only a CI environment can run this lane"
  end
  prepare_lane_options(
    options: options,
    mapping: {
      :workspace => {:env_var => "DG_WORKSPACE"},
      :project => {:env_var => "DG_PROJECT"},
      :scheme => {:env_var => "DG_SCHEME"}
    }
  )
  if files_matching(pattern: "Podfile") != nil
    cocoapods()
  end
  scan(
    workspace: options[:workspace],
    project: options[:project],
    scheme: options[:scheme],
    skip_slack: options[:skip_slack],
    clean: true
  )
end

desc "CI deployment lane, do something only on a master branch"
desc "Deploy to **github**, **carthage** and **cocoapods**"
desc "#### How to install ?"
desc "This lane require actions or lanes define in [Digipolitan/fastlane-ios-framework](https://github.com/Digipolitan/fastlane-ios-framework)"
desc "- `framework_deploy_github` lane **if github_repository_name != nil**"
desc "- `framework_deploy_cocoapods` lane **if skip_cocoapods != true**"
desc "```\nimport_from_git(\n  url: 'https://github.com/Digipolitan/fastlane-ios-framework'\n)\n```"
desc "#### Options"
desc "* **github_repository_name**: The GitHub repository name such as 'company/project'"
desc "  * **environment_variable**: DG_GITHUB_REPOSITORY_NAME"
desc "  * **type**: string"
desc "  * **optional**: true"
desc "* **workspace**: The workspace to use."
desc "  * **environment_variable**: DG_WORKSPACE"
desc "  * **type**: string"
desc "  * **optional**: true"
desc "* **project**: The project to use."
desc "  * **environment_variable**: DG_PROJECT"
desc "  * **type**: string"
desc "  * **optional**: true"
desc "* **scheme**: The scheme into the workspace to execute."
desc "  * **environment_variable**: DG_SCHEME"
desc "  * **type**: string"
desc "  * **optional**: true"
desc "* **product_name**: The framework name."
desc "  * **environment_variable**: DG_PRODUCT_NAME"
desc "  * **type**: string"
desc "  * **optional**: true"
desc "* **skip_slack**: Skip slack notification even if a SLACK_URL is define."
desc "  * **type**: boolean"
desc "  * **optional**: true"
desc "  * **default_value**: false"
desc "* **skip_cocoapods**: Skip cocoapods deployment"
desc "  * **type**: boolean"
desc "  * **optional**: true"
desc "  * **default_value**: false"
desc "* **skip_carthage**: Skip carthage deployment"
desc "  * **type**: boolean"
desc "  * **optional**: true"
desc "  * **default_value**: false"
desc "#### Environment variables"
desc "* **SLACK_URL**: The slack Hook URL"
desc "  * **type**: string"
desc "  * **optional**: true"
desc ""
lane :ci_framework_deploy do |options|
  if ENV['CI'] == nil
    UI.user_error! "Only a CI environment can run this lane"
  end
  branch = git_branch()
  if branch == "master"
    prepare_lane_options(
      options: options,
      mapping: {
        :github_repository_name => {:env_var => "GITHUB_REPOSITORY_NAME"},
        :github_token => {:env_var => "GITHUB_TOKEN"},
        :podspec_path => {:env_var => "DG_PODSPEC_PATH"},
        :project => {:env_var => "DG_PROJECT"},
        :product_name => {:env_var => "DG_PRODUCT_NAME"}
      }
    )
    notification_payload = {
      "Git Branch" => branch,
      "Version" => get_version_number(xcodeproj: options[:project]),
      "Platform" => "iOS"
    }
    if options[:skip_carthage] != true
      carthage(
        command: "build",
        platform: "all",
        no_skip_current: true
      )
      carthage(command: "archive")
    end
    if options[:github_repository_name] != nil
      framework_deploy_github(
        token: options[:github_token],
        repository_name: options[:github_repository_name],
        project: options[:project],
        skip_carthage: options[:skip_carthage]
      )
      notification_payload["GitHub Release"] = lane_context[:SET_GITHUB_RELEASE_HTML_LINK]
    end
    if options[:skip_cocoapods] != true
      framework_deploy_cocoapods(podspec_path: options[:podspec_path])
      notification_payload["CocoaPods"] = lane_context[:DG_COCOAPODS_RELEASE_LINK]
    end

    if options[:skip_slack] != true
      slack(
        message: "Successfully distributed framework CI",
        payload: notification_payload,
        default_payloads: []
      )
    end
  else
    UI.message "Nothing to deploy on branch '#{branch}', deploy only on the master branch"
  end
end
